MVC API EntityFramework/SmartHomeMVC/Models/Alarm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHomeMVC.Models
{
    public class Alarm : Gadget
    {
        public int Id { get; set; }
        public string title { get; set; }
        private bool condition;
        public bool Condition
        {
            get { return condition; }
            set
            {
                condition = value;
            }
        }
        public Alarm(string title)
            : base(title)
        {
            this.title = title;
        }
        public Alarm()
        {

        }
        public override bool CurrentCondition()
        {
            return condition;
        }
        public override string GadgetTitle()
        {
            return title;
        }
        public bool PowerOn()
        {
            return condition = true;
        }
        public bool PowerOff()
        {
            return condition = false;
        }
        public override string ToString()
        {
            string condition;
            if (this.condition)
            {
                condition = "Включен";
            }
            else
            {
                condition = "Выключен";
            }
            return condition;
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Controllers/AlarmController.cs
using SmartHomeMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartHomeMVC.Controllers
{
    public class AlarmController : Controller
    {
        SmartHomeContext db = new SmartHomeContext();

        public ActionResult AlarmSH()
        {    
            IEnumerable<Alarm> Alarms = db.Alarms;
            ViewBag.Alarms = Alarms;
            return View();
        }

        [HttpGet]
        public ActionResult AlarmCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AlarmCreate(Alarm al)
        {
            db.Alarms.Add(al);
            db.SaveChanges();
            return RedirectToAction("AlarmSH");
        }

        [HttpGet]
        public ActionResult AlarmEditPartial(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Alarm al = db.Alarms.Find(id);

            if (al == null)
            {
                return HttpNotFound();
            }
            return PartialView(al);
        }

        [HttpPost]
        public ActionResult AlarmEditPartial(Alarm al)
        {
            db.Entry(al).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AlarmSH");
        }

        [HttpGet]
        public ActionResult AlarmDelete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Alarm al = db.Alarms.Find(id);
            if (al == null)
            {
                return HttpNotFound();
            }
            return View(al);
        }

        [HttpPost, ActionName("AlarmDelete")]
        public ActionResult AlarmDeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Alarm al = db.Alarms.Find(id);
            if (al == null)
            {
                return HttpNotFound();
            }
            db.Alarms.Remove(al);
            db.SaveChanges();
            return RedirectToAction("AlarmSH");
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Views/Alarm/AlarmCreate.cshtml
@model SmartHomeMVC.Models.Alarm

<h4>Новое устройство</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.title, "Название")
    <br />
    @Html.EditorFor(model => model.title)
    <br /><br />
    @Html.LabelFor(model => model.Condition, "Включить")
    <br />
    @Html.EditorFor(model => model.Condition)
    <br /><br />
    <input type="submit" value="Добавить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Alarm/AlarmDelete.cshtml
@model SmartHomeMVC.Models.Alarm
<h4>Удаление устройства</h4>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.title)
    </dd>
</dl>

<p>Для удаления данного устройства нажмите кнопку "Удалить"</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Alarm/AlarmEditPartial.cshtml
@model SmartHomeMVC.Models.Alarm

@using (Html.BeginForm("AlarmEditPartial", "Alarm", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.title, "Название")
            <br />
            @Html.EditorFor(m => m.title)
        </p>
        <p>
            @Html.LabelFor(m => m.Condition, "Включить")
            <br />
            @Html.EditorFor(m => m.Condition)

        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

MVC API EntityFramework/SmartHomeMVC/Views/Alarm/AlarmSH.cshtml
@{
    ViewBag.Title = "Alarm";
    ViewBag.Header = "ALARM";
    Layout = "~/Views/_MasterPage.cshtml";
}

<div>
    <a href="/Alarm/AlarmCreate"><b>Добавить новое устройство</b></a>
</div>
<br />
<div>
    <h4>Текущие объекты "Сигнализация":</h4>
    <div>
        @foreach (var A in @ViewBag.Alarms)
        {
            string onOff;
            if (A.Condition == true)
            {
                onOff = "Устройство включено";
            }
            else { onOff = "Устройство выключено"; }
            <table class="table table-bordered table-striped text-center">
                <tr>
                    <td><p>Название &nbsp;</p></td>
                    <td><p>Состояние &nbsp;</p></td>
                    <td><p>Настройка &nbsp;</p></td>
                    <td><p>Удаление</p></td>
                </tr>
                <tr>
                    <td><p>@A.title &nbsp;</p></td>
                    <td><p>@onOff &nbsp;</p></td>
                    <td><p><a href="/Alarm/AlarmEditPartial/@A.Id"><b>Настроить&nbsp;</b></a></p></td>
                    <td><p><a href="/Alarm/AlarmDelete/@A.Id"><b>Удалить</b></a></p></td>
                </tr>
            </table>
        }
    </div>
</div>