MVC API EntityFramework/SmartHomeMVC/Models/Climate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHomeMVC.Models
{
    public class Climate : Gadget
    {
        public int Id { get; set; }
        public string title { get; set; }
        private bool condition = false;
        public int temperature { get; set; }
        public bool Condition
        {
            get { return condition; }
            set
            {
                condition = value;
            }
        }
        public Climate(string title)
            : base(title)
        {
            this.title = title;
        }
        public Climate()
        {

        }
        public override bool CurrentCondition()
        {
            return condition;
        }
        public override string GadgetTitle()
        {
            return title;
        }
        public int TemperatureValue()
        {
            return temperature;
        }
        public bool PowerOn()
        {
            return condition = true;
        }
        public bool PowerOff()
        {
            return condition = false;
        }
        public void TemperatureUp()
        {
            if (15 < temperature && temperature < 29)
            {
                temperature += 1;
            }
        }
        public void TemperatureDown()
        {
            if (17 < temperature && temperature < 31)
            {
                temperature -= 1;
            }
        }
        public void TemperatureSet(int value)
        {
            if (15 < value && value < 31)
            {
                temperature = value;
            }
        }
        public override string ToString()
        {
            string condition;
            if (this.condition)
            {
                condition = "Включен";
            }
            else
            {
                condition = "Выключен";
            }
            return condition +", "+ "Температура установлена на: " + temperature.ToString() + "град.";
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Controllers/ClimateController.cs
using SmartHomeMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartHomeMVC.Controllers
{
    public class ClimateController : Controller
    {
        SmartHomeContext db = new SmartHomeContext();

        public ActionResult ClimateSH()
        {
            IEnumerable<Climate> Climates = db.Climates;
            ViewBag.Climates = Climates;
            return View();
        }

        [HttpGet]
        public ActionResult ClimateCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ClimateCreate(Climate clm)
        {
            db.Climates.Add(clm);
            db.SaveChanges();
            return RedirectToAction("ClimateSH");
        }

        [HttpGet]
        public ActionResult ClimateEditPartial(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Climate clm = db.Climates.Find(id);

            if (clm == null)
            {
                return HttpNotFound();
            }
            return PartialView(clm);
        }

        [HttpPost]
        public ActionResult ClimateEditPartial(Climate clm)
        {
            db.Entry(clm).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ClimateSH");
        }

        [HttpGet]
        public ActionResult ClimateDelete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Climate clm = db.Climates.Find(id);
            if (clm == null)
            {
                return HttpNotFound();
            }
            return View(clm);
        }

        [HttpPost, ActionName("ClimateDelete")]
        public ActionResult ClimateDeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Climate clm = db.Climates.Find(id);
            if (clm == null)
            {
                return HttpNotFound();
            }
            db.Climates.Remove(clm);
            db.SaveChanges();
            return RedirectToAction("ClimateSH");
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Views/Climate/ClimateCreate.cshtml
@model SmartHomeMVC.Models.Climate

<h4>Новое устройство</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.title, "Название")
    <br />
    @Html.EditorFor(model => model.title)
    <br /><br />
    @Html.LabelFor(model => model.Condition, "Включить")
    <br />
    @Html.EditorFor(model => model.Condition)
    <br /><br />
    @Html.LabelFor(model => model.temperature, "Установить температуру")
    <br />
    @Html.EditorFor(model => model.temperature)
    <br /><br />
    <input type="submit" value="Добавить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Climate/ClimateDelete.cshtml
@model SmartHomeMVC.Models.Climate
<h4>Удаление устройства</h4>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.title)
    </dd>
</dl>

<p>Для удаления данного устройства нажмите кнопку "Удалить"</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Climate/ClimateEditPartial.cshtml
@model SmartHomeMVC.Models.Climate

@using (Html.BeginForm("ClimateEditPartial", "Climate", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.title, "Название")
            <br />
            @Html.EditorFor(m => m.title)
        </p>
        <p>
            @Html.LabelFor(m => m.Condition, "Включить")
            <br />
            @Html.EditorFor(m => m.Condition)

        </p>
        <p>
            @Html.LabelFor(m => m.temperature, "Установить температуру")
            <br />
            @Html.EditorFor(m => m.temperature)

        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

MVC API EntityFramework/SmartHomeMVC/Views/Climate/ClimateSH.cshtml
@{
    ViewBag.Title = "Climate";
    ViewBag.Header = "CLIMATE";
    Layout = "~/Views/_MasterPage.cshtml";
}

<div>
    <a href="/Climate/ClimateCreate"><b>Добавить новое устройство</b></a>
</div>
<br />
<div>
    <h4>Текущие объекты "Кондиционер":</h4>
    <div>
        @foreach (var A in @ViewBag.Climates)
        {
            string onOff;
            string vision;
            if (A.Condition == true)
            {
                onOff = "Включен";
                vision = "visionOn";
            }
            else { onOff = "Выключен"; vision = "visionOff"; }
            <table class="table table-bordered table-striped text-center">
                <tr>
                    <td><p>Название &nbsp;</p></td>
                    <td><p>Состояние &nbsp;</p></td>
                    <td><p>Температура &nbsp;</p></td>
                    <td><p>Настройка &nbsp;</p></td>
                    <td><p>Удаление</p></td>
                </tr>
                <tr>
                    <td><p>@A.title &nbsp;</p></td>
                    <td><p>@onOff &nbsp;</p></td>
                    <td><p class="@vision">@A.temperature &nbsp;</p></td>
                    <td><p><a href="/Climate/ClimateEditPartial/@A.Id"><b>Настроить&nbsp;</b></a></p></td>
                    <td><p><a href="/Climate/ClimateDelete/@A.Id"><b>Удалить</b></a></p></td>
                </tr>
            </table>
        }
    </div>
</div>