MVC API EntityFramework/SmartHomeMVC/Models/TV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHomeMVC.Models
{
    public class TV : HomeGoods
    {
        public int Id { get; set; }
        public string title {get; set; }
        private bool condition;
        public int channel { get; set; }
        public int volume { get; set; }
        public bool Condition
        {
            get { return condition; }
            set 
            { 
                condition = value;
            }
        }
        public TV(string title)
            : base(title)
        {
            this.title = title;
        }
        public TV()
        {

        }
        public override bool CurrentCondition()
        {
            return condition;
        }
        public override string GadgetTitle()
        {
            return title;
        }
        public void ChangeChannel(int userChannel)
        {
            if (0 < userChannel && userChannel < 101)
            {
                channel = userChannel;
            }
        }
        public int CurrentChannel()
        {
            return channel;
        }
        public void VolumeUp()
        {
            if (0 <= volume && volume < 99)
            {
                volume += 1;
            }
        }
        public void VolumeDown()
        {
            if (1 <= volume && volume < 99)
            {
                volume -= 1;
            }
        }
        public void Mute()
        {
            volume = 0;
        }
        public int CurrentVolume()
        {
            return volume;
        }
        public bool PowerOn()
        {
            return condition = true;
        }
        public bool PowerOff()
        {
            return condition = false;
        }
        public void ChannelUp()
        {
            if (0 <= channel && channel < 99)
            {
                channel += 1;
            }
        }
        public void ChannelDown()
        {
            if (1 <= channel && channel < 99)
            {
                channel -= 1;
            }
        }
        public override string ToString()
        {
            string condition;
            if (this.condition)
            {
                condition = "Включен";
            }
            else
            {
                condition = "Выключен";
            }
            return condition + ", " + "Установлен канал: " + channel.ToString() +", "+ "Громкость установлена на: " + volume.ToString();
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Controllers/TVAPIController.cs
using SmartHomeMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;

namespace SmartHomeMVC.Controllers
{
    public class TVAPIController : ApiController
    {
        SmartHomeContext db = new SmartHomeContext();

        public IEnumerable<TV> GetAllTVs()
        {
            return db.TVs;
        }

        public TV GetTV(int id)
        {
            TV tv = db.TVs.Find(id);
            return tv;
        }

        [HttpPost]
        public void CreateTV([FromBody]TV tv)
        {
            db.TVs.Add(tv);
            db.SaveChanges();
        }

        [HttpPut]
        public void EditTV(int id, [FromBody]TV tv)
        {
            if (id == tv.Id)
            {
                db.Entry(tv).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
        }

        public void DeleteTV(int id)
        {
            TV tv = db.TVs.Find(id);
            if (tv != null)
            {
                db.TVs.Remove(tv);
                db.SaveChanges();
            }
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Controllers/TVController.cs
using SmartHomeMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartHomeMVC.Controllers
{
    public class TVController : Controller
    {
        SmartHomeContext db = new SmartHomeContext();

        public ActionResult TVSH()
        {
            IEnumerable<TV> TVs = db.TVs;
            ViewBag.TVs = TVs;
            return View();
        }

        [HttpGet]
        public ActionResult TVCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TVCreate(TV tv)
        {
            db.TVs.Add(tv);
            db.SaveChanges();
            return RedirectToAction("TVSH");
        }

        [HttpGet]
        public ActionResult TVEditPartial(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            TV tv = db.TVs.Find(id);

            if (tv == null)
            {
                return HttpNotFound();
            }
            return PartialView(tv);
        }

        [HttpPost]
        public ActionResult TVEditPartial(TV tv)
        {
            db.Entry(tv).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("TVSH");
        }

        [HttpGet]
        public ActionResult TVDelete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            TV tv = db.TVs.Find(id);
            if (tv == null)
            {
                return HttpNotFound();
            }
            return View(tv);
        }

        [HttpPost, ActionName("TVDelete")]
        public ActionResult TVDeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            TV tv = db.TVs.Find(id);
            if (tv == null)
            {
                return HttpNotFound();
            }
            db.TVs.Remove(tv);
            db.SaveChanges();
            return RedirectToAction("TVSH");
        }

        public ActionResult TVAPI()
        {
            return View();
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Views/TV/TVAPI.cshtml
@{
    ViewBag.Title = "TV";
    ViewBag.Header = "TV API";
    Layout = "~/Views/_MasterPage.cshtml";
}

<div id="tableBlock"></div>
<div id="editBlock">
    <p><b>Настройки</b></p>
    <table>
        <tr>
            <td>
                <input type="hidden" id="editId" />
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                <label>Название: </label>
            </td>
            <td>
                <input type="text" id="editTitle" />
            </td>
        </tr>
        <tr>
            <td>
                <label>Состояние: </label>
            </td>
            <td>
                <input type="text" id="editCondition" />
            </td>
        </tr>
        <tr>
            <td>
                <label>Канал: </label>
            </td>
            <td>
                <input type="text" id="editChannel" />
            </td>
        </tr>
        <tr>
            <td>
                <label>Громкость: </label>
            </td>
            <td>
                <input type="number" id="editVolume" />
            </td>
        </tr>
    </table>
    <button id="editTV">Применить</button>
</div>
<div id="createBlock">
    <p><b>Добавить устройство</b></p>
    <table>
        <tr>
            <td>
                <label>Название: </label>
            </td>
            <td>
                <input type="text" id="addTitle" />
            </td>
        </tr>
    </table>
    <br />
    <button id="addTV">Применить</button>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        GetAllTVs();

        $("#editTV").click(function (event) {
            event.preventDefault();
            EditTV();
        });
        $("#addTV").click(function (event) {
            event.preventDefault();
            AddTV();
        });

    });

    // Список всех устройств
    function GetAllTVs() {

        $("#createBlock").css('display', 'block');
        $("#editBlock").css('display', 'none');
        $.ajax({
            url: '/api/tvapi/',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                ShowResult(data);
            },
        });
    }

    // Добавление нового устройства
    function AddTV() {
        // получаем имя и состояние
        var TV = {
            Title: $('#addTitle').val(),
        };
        if ($('#addTitle').val() == "") {
            alert("Введите имя устройства!")
        }
        else {
            $.ajax({
                url: '/api/tvapi/',
                type: 'POST',
                data: JSON.stringify(TV),
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    GetAllTVs();
                },
            });
        }
    }

    // Удаление устройства
    function DeleteTV(id) {

        $.ajax({
            url: '/api/tvapi/' + id,
            type: 'DELETE',
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                GetAllTVs();
            },
        });
    }

    // Настройка устройства
    function EditTV() {
        var id = $('#editId').val()
        var conditionInputed;
        if ($('#editCondition').val() == 'True') {
            conditionInputed = 'true';
        }
        else if ($('#editCondition').val() == 'true') {
            conditionInputed = true;
        }
        else if ($('#editCondition').val() == 'Вкл') {
            conditionInputed = true;
        }
        else if ($('#editCondition').val() == 'вкл') {
            conditionInputed = true;
        }
        else if ($('#editCondition').val() == '1') {
            conditionInputed = true;
        }
        else if ($('#editCondition').val() == 'On') {
            conditionInputed = true;
        }
        else if ($('#editCondition').val() == 'on') {
            conditionInputed = true;
        }
        else (conditionInputed = false)

        // получаем новые значения
        var TV = {
            Id: $('#editId').val(),
            title: $('#editTitle').val(),
            Condition: conditionInputed,
            channel: $('#editChannel').val(),
            volume: $('#editVolume').val(),
        };
        $.ajax({
            url: '/api/tvapi/' + id,
            type: 'PUT',
            data: JSON.stringify(TV),
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                GetAllTVs();
            },
        });
    }

    // вывод полученных данных на экран
    function ShowResult(TVs) {
        var onOff;
        var vision;
        var strResult = "<table class='table table-bordered'><th>ID</th><th>Название </th><th>Состояние </th><th>Канал </th><th>Громкость </th><th>Настройки </th><th>Удаление </th>";
        $.each(TVs, function (index, TV) {
            if (TV.Condition == false) {
                onOff = "Выкл";
                vision = "visionOff";
            }
            else {
                onOff = "Вкл";
                vision = "visionOn";
            }
            strResult += "<tr><td>" + TV.Id + "</td><td> " + TV.title + "</td><td>" + onOff + "</td><td class= '" + vision + "'>" + TV.channel + "</td><td class= '" + vision + "'>" + TV.volume +
            "</td><td><a id='editItem' data-item='" + TV.Id + "' onclick='EditItem(this);' >Настроить</a></td>" +
            "<td><a id='delItem' data-item='" + TV.Id + "' onclick='DeleteItem(this);' >Удалить</a></td></tr>";
        });
        strResult += "</table>";
        $("#tableBlock").html(strResult);

    }

    // обработчик удаления
    function DeleteItem(el) {
        // получаем id удаляемого объекта
        var id = $(el).attr('data-item');
        DeleteTV(id);
    }

    // обработчик редактирования
    function EditItem(el) {
        // получаем id редактируемого объекта
        var id = $(el).attr('data-item');
        GetTV(id);
    }

    // вывод текущих настроек устройства в поля для редактирования
    function ShowTV(TV) {
        if (TV != null) {
            $("#createBlock").css('display', 'none');
            $("#editBlock").css('display', 'block');
            $("#editId").val(TV.Id);
            $("#editTitle").val(TV.Title);
            $("#editChannel").val(TV.Channel);
            $("#editVolume").val(TV.Volume);
        }
        else {
            alert("Устройство не найдено");
        }
    }

    // поиск устройства для редактирования
    function GetTV(id) {
        $.ajax({
            url: '/api/tvapi/' + id,
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                ShowTV(data);
            },
        });
    }
</script>

MVC API EntityFramework/SmartHomeMVC/Views/TV/TVCreate.cshtml
@model SmartHomeMVC.Models.TV

<h4>Новое устройство</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.title, "Название")
    <br />
    @Html.EditorFor(model => model.title)
    <br /><br />
    @Html.LabelFor(model => model.Condition, "Включить")
    <br />
    @Html.EditorFor(model => model.Condition)
    <br /><br />
    @Html.LabelFor(model => model.channel, "Канал")
    <br />
    @Html.EditorFor(model => model.channel)
    <br /><br />
    @Html.LabelFor(model => model.volume, "Громкость")
    <br />
    @Html.EditorFor(model => model.volume)
    <br /><br />
    <input type="submit" value="Добавить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/TV/TVDelete.cshtml
@model SmartHomeMVC.Models.TV 
<h4>Удаление устройства</h4>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.title)
    </dd>
</dl>

<p>Для удаления данного устройства нажмите кнопку "Удалить"</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/TV/TVEditPartial.cshtml
@model SmartHomeMVC.Models.TV

@using (Html.BeginForm("TVEditPartial", "TV", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.title, "Название")
            <br />
            @Html.EditorFor(m => m.title)
        </p>
        <p>
            @Html.LabelFor(m => m.Condition, "Включить")
            <br />
            @Html.EditorFor(m => m.Condition)
        </p>
        <p>
            @Html.LabelFor(m => m.channel, "Установить канал")
            <br />
            @Html.EditorFor(m => m.channel)
        </p>
        <p>
            @Html.LabelFor(m => m.volume, "Установить громкость")
            <br />
            @Html.EditorFor(m => m.volume)
        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

MVC API EntityFramework/SmartHomeMVC/Views/TV/TVSH.cshtml
@{
    ViewBag.Title = "TV";
    ViewBag.Header = "TV";
    Layout = "~/Views/_MasterPage.cshtml";
}
<div class="text-right">
    @Html.ActionLink("Версия Web API", "TVAPI", "TV")
</div>
<br />
<div>
    <a href="/TV/TVCreate"><b>Добавить новое устройство</b></a>
</div>
<br />
<div>
    <h4>Текущие объекты "TV":</h4>
    <div>
        @foreach (var A in @ViewBag.TVs)
        {
            string onOff;
            string vision;
            if (A.Condition == true)
            {
                onOff = "Вкл";
                vision = "visionOn";
            }
            else { onOff = "Выкл"; vision = "visionOff"; }
            <table class="table table-bordered table-striped text-center">
                <tr>
                    <td><p>Название &nbsp;</p></td>
                    <td><p>Состояние &nbsp;</p></td>
                    <td><p>Канал &nbsp;</p></td>
                    <td><p>Громкость &nbsp;</p></td>
                    <td><p>Настройка &nbsp;</p></td>
                    <td><p>Удаление</p></td>
                </tr>
                <tr>
                    <td><p>@A.title &nbsp;</p></td>
                    <td><p>@onOff &nbsp;</p></td>
                    <td><p class="@vision">@A.channel &nbsp;</p></td>
                    <td><p class="@vision">@A.volume &nbsp;</p></td>
                    <td><p><a href="/TV/TVEditPartial/@A.Id"><b>Настроить&nbsp;</b></a></p></td>
                    <td><p><a href="/TV/TVDelete/@A.Id"><b>Удалить</b></a></p></td>
                </tr>
            </table>
        }
    </div>
</div>