MVC API EntityFramework/SmartHomeMVC/Models/Freedge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHomeMVC.Models
{
    public class Freedge : HomeGoods
    {
        public int Id { get; set; }
        public string title { get; set; }
        private bool condition;
        public int temperature {get; set; }
        public bool Condition
        {
            get { return condition; }
            set
            {
                condition = value;
            }
        }
        public Freedge(string title)
            : base(title)
        {
            this.title = title;
        }
        public Freedge()
        {

        }
        public override bool CurrentCondition()
        {
            return condition;
        }
        public override string GadgetTitle()
        {
            return title;
        }
        public int TemperatureValue()
        {
            return temperature;
        }
        public bool PowerOn()
        {
            return condition = true;
        }
        public bool PowerOff()
        {
            return condition = false;
        }
        public bool Open()
        {
            return condition = true;
        }
        public bool Close()
        {
            return condition = false;
        }
        public void TemperatureUp()
        {
            if (-1 < temperature && temperature < 4)
            {
                temperature += 1;
            }
        }
        public void TemperatureDown()
        {
            if (0 < temperature && temperature < 5)
            {
                temperature -= 1;
            }
        }
        public void TemperatureSet(int value)
        {
            if (-2 < value && value < 6)
            {
                temperature = value;
            }
        }
        public override string ToString()
        {
            string condition;
            if (this.condition)
            {
                condition = "Включен";
            }
            else
            {
                condition = "Выключен";
            }
            return condition + ", " + "Температура внутри установлена на: " + temperature.ToString() + "град.";
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Controllers/FreedgeController.cs
using SmartHomeMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartHomeMVC.Controllers
{
    public class FreedgeController : Controller
    {
        SmartHomeContext db = new SmartHomeContext();

        public ActionResult FreedgeSH()
        {
            IEnumerable<Freedge> Freedges = db.Freedges;
            ViewBag.Freedges = Freedges;
            return View();
        }

        [HttpGet]
        public ActionResult FreedgeCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FreedgeCreate(Freedge clm)
        {
            db.Freedges.Add(clm);
            db.SaveChanges();
            return RedirectToAction("FreedgeSH");
        }

        [HttpGet]
        public ActionResult FreedgeEditPartial(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Freedge clm = db.Freedges.Find(id);

            if (clm == null)
            {
                return HttpNotFound();
            }
            return PartialView(clm);
        }

        [HttpPost]
        public ActionResult FreedgeEditPartial(Freedge clm)
        {
            db.Entry(clm).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("FreedgeSH");
        }

        [HttpGet]
        public ActionResult FreedgeDelete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Freedge clm = db.Freedges.Find(id);
            if (clm == null)
            {
                return HttpNotFound();
            }
            return View(clm);
        }

        [HttpPost, ActionName("FreedgeDelete")]
        public ActionResult FreedgeDeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Freedge clm = db.Freedges.Find(id);
            if (clm == null)
            {
                return HttpNotFound();
            }
            db.Freedges.Remove(clm);
            db.SaveChanges();
            return RedirectToAction("FreedgeSH");
        }
    }
}

MVC API EntityFramework/SmartHomeMVC/Views/Freedge/FreedgeCreate.cshtml
@model SmartHomeMVC.Models.Freedge

<h4>Новое устройство</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.title, "Название")
    <br />
    @Html.EditorFor(model => model.title)
    <br /><br />
    @Html.LabelFor(model => model.Condition, "Включить")
    <br />
    @Html.EditorFor(model => model.Condition)
    <br /><br />
    @Html.LabelFor(model => model.temperature, "Установить температуру внутри холодильника")
    <br />
    @Html.EditorFor(model => model.temperature)
    <br /><br />
    <input type="submit" value="Добавить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Freedge/FreedgeDelete.cshtml
@model SmartHomeMVC.Models.Freedge
<h4>Удаление устройства</h4>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.title)
    </dd>
</dl>

<p>Для удаления данного устройства нажмите кнопку "Удалить"</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

MVC API EntityFramework/SmartHomeMVC/Views/Freedge/FreedgeEditPartial.cshtml
@model SmartHomeMVC.Models.Freedge

@using (Html.BeginForm("FreedgeEditPartial", "Freedge", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        <p>
            @Html.LabelFor(m => m.title, "Название")
            <br />
            @Html.EditorFor(m => m.title)
        </p>
        <p>
            @Html.LabelFor(m => m.Condition, "Включить")
            <br />
            @Html.EditorFor(m => m.Condition)

        </p>
        <p>
            @Html.LabelFor(m => m.temperature, "Установить температуру")
            <br />
            @Html.EditorFor(m => m.temperature)

        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

MVC API EntityFramework/SmartHomeMVC/Views/Freedge/FreedgeSH.cshtml
@{
    ViewBag.Title = "Freedge";
    ViewBag.Header = "FREEDGE";
    Layout = "~/Views/_MasterPage.cshtml";
}

<div>
    <a href="/Freedge/FreedgeCreate"><b>Добавить новое устройство</b></a>
</div>
<br />
<div>
    <h4>Текущие объекты "Холодильник":</h4>
    <div>
        @foreach (var A in @ViewBag.Freedges)
        {
            string onOff;
            string vision;
            if (A.Condition == true)
            {
                onOff = "Включен";
                vision = "visionOn";
            }
            else { onOff = "Выключен"; vision = "visionOff"; }
            <table class="table table-bordered table-striped text-center">
                <tr>
                    <td><p>Название &nbsp;</p></td>
                    <td><p>Состояние &nbsp;</p></td>
                    <td><p>Температура внутри, град. &nbsp;</p></td>
                    <td><p>Настройка &nbsp;</p></td>
                    <td><p>Удаление</p></td>
                </tr>
                <tr>
                    <td><p>@A.title &nbsp;</p></td>
                    <td><p>@onOff &nbsp;</p></td>
                    <td><p class="@vision">@A.temperature &nbsp;</p></td>
                    <td><p><a href="/Freedge/FreedgeEditPartial/@A.Id"><b>Настроить&nbsp;</b></a></p></td>
                    <td><p><a href="/Freedge/FreedgeDelete/@A.Id"><b>Удалить</b></a></p></td>
                </tr>
            </table>
        }
    </div>
</div>